      real(dp), parameter :: tiny_sp = 10._dp**(-precision(1._sp))
      real(dp), parameter :: tiny_dp = 10._dp**(-precision(1._dp))
      real(dp), parameter :: tiny_ex = 10._dp**(-precision(1._ex))
      real(dp), parameter :: tiny_qp = 10._dp**(-precision(1._qp))
      real(dp), parameter :: tiny = 10._dp**(-precision(1._dp))
