#!/bin/bash

STRING=D_BSM_o_SM_DBKG_0_0
STEP=0.05
MIN=0.0
MAX=2.0
MAX=$(echo $MAX + $STEP | bc)
CUT=0.0

rm -f run_list.txt
cd ../WORK
rm -f logs/*
mkdir RUNS_${STRING}
cp ../Configurations/input_ggZZ_signal.DAT .
sed -e "s/DCUT/${CUT}d0/" ../Configurations/input_qqZZ_81.DAT > RUNS_${STRING}/input_qqZZ_81.DAT

i=${MIN}

for i in `seq $MIN $STEP $MAX`
do  
  i=$(echo $i | awk '{printf "%.2f", $0}')
  j=$(echo 1 - $i | bc | awk '{printf "%.2f", $0}')
  sed -e "s/CT/${i}d0/" -e "s/CG/${j}d0/" -e "s/CV/1.0d0/" -e "s/CA/1.0d0/" -e "s/DCUT/${CUT}d0/" -e "s/RUN/13T_${i}/" input_ggZZ_signal.DAT > RUNS_${STRING}/input_ggZZ_signal_${i}.DAT
  echo "RUNS_${STRING}, input_ggZZ_signal_${i}.DAT" >> run_list.txt
done
rm input_ggZZ_signal.DAT
echo "RUNS_${STRING}, input_qqZZ_81.DAT" >> run_list.txt
mv run_list.txt ../Bin/.
cd ../Bin
condor_submit submit_condor.sh
